version: "3"
services:
  webapp:
    build: ./
    container_name: "webapp"
    ports:
      - "3000:3000"
    links:
      - "mongodb"
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo
    volumes:
          - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"