version: "3"
services:
  app:
    build: .
    environment:
      - DB_HOST=node_db
    ports:
      - 3000
    depends_on:
      - db
  db:
    container_name: node_db
    image: mongo
    environment:
      - SERVICE_NAME=node_db
    ports:
      - 27017