version: "3"
services:
  app:
    build: .
    container_name: node_db
    hostname: app
    environment:
      - DB_HOST=node_db
    ports:
      - 3000
    networks:
      app_net:
        ipv4_address: 172.16.238.10
    links:
      - db
  db:
    image: mongo
    container_name: node_db
    hostname: db
    environment:
      - SERVICE_NAME=node_db
    ports:
      - 27017
    networks:
      app_net:
        ipv4_address: 172.16.238.11

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24