version: '3'

services:
  webapp:
    build: ./
    container_name: nickel-infinite-app
    hostname: nickel-infinite-webapp
    ports:
      - "3000:3000"
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    container_name: nickel-infinite-app
    hostname: nickel-infinite-database
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"