version: "3"
services:
  web:
    build: ./
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
  db:
    image: mongo:latest
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"