version: "3"
services:
  webapp:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: mongo:latest
    volumes:
      - /data/mongodb/db:/data/db
    ports:
      - "27017:27017"